### ISSUE TITLE
error dialog- centrality mapper error when only using 2 cores

### ISSUE THREAD

**Issue by johngallo** [linkagescape/linkage-mapper#106]
A user got an error when they tried this, and it may simply be because there is no central core.  If that is the case, thenwe can update the error dialog to state this, and that 3 or more cores are needed for centrality mapper to work.  Or it was an error in their settings (see personal email to John on 6/29/20 at 4:38 AM)

**Comment by dkav** [comment]
@johngallo can you include the error message?

**Comment by johngallo** [comment]
Thanks @dkav  I was moving too fast. This was the message that was sent to me:

"Dear John,

 

I’m trying to use tiger data of Nepal to come up with potential connectivity using Linkage Mapper tools. I’m following Glover-Kapfer 2015 and Dutta et al (2015) as they very much conforms with what we’ve trying to come up with.

 

I’m facing an issue which I couldn’t find anywhere- google group and github. I tried posting the issue there but struggled to find one so I was left with only option of emailing you. Sorry to bother you like this but after several days of fixing the issues I’m stuck with one final step and I can’t seem to fix it no matter how much I try. Would be a great help if you could look into the errors.

 

Main issue: Using centrality mapper (the others worked well- build network and map linkages, pinchpoint mapper and circuitscape for ArcGIS under Circuitscape tool (BETA TESTING)).

 

My input files: Resistance file of 100 meter resolution of 8.86 MB file size with 1758 nodes.

Core area: Just a pair of PA for now.

My work process: I used the same project directory where I had successfully ran build network and map linkages, pinchpoint mapper and circuitscape tool. Used the same core area files. For pinchpoint, I even checked raster centrality using circuitscape option (I wonder what is the difference between this and centrality standalone tool).

 

My program details:

ArcGIS 10.8 version
Linkage mapper 2.0.0
Circuitscape standalone software- 4.0.5 and Circuitscape for ArcGIS tool (BETA TESTING).
 

 

Issue box:

 

Executing: CentralityMapper C:\LM_Tiger\Output C:\LM_Tiger\Input\ShNP_Doti\ShNP_Doti.shp Core_ID

Start Time: Mon Jun 29 17:03:50 2020

Running script CentralityMapper...

---------------------------------

A record of run settings and messages can be found in your log directory:

C:\LM_Tiger\Output\run_history\log

---------------------------------


 

********************************************************

NOTE: Linkage Mapper tools often work best when run  from ArcCatalog instead of ArcMap.

 

Setting data frame spatial reference to that of core area feature class.

Creating output folder: C:\LM_Tiger\Output\centrality_tmp

---------------------------------

Running script s7_centrality.py


---------------------------------

Mapping centrality of network cores and links

using Circuitscape....

---------------------------------

 

Looking for C:\LM_Tiger\Output\datapass\linkTable_s5_plus.csv

There are 1 links in the table.

This includes 1 potential corridor links.

---------------------------------

 

Calculating current flow centrality using Circuitscape...

     Calling Circuitscape:

 

Circuitscape failed.

      Traceback (most recent call last):

        File "csrun.py", line 13, in <module>

        File "circuitscape\profiler.pyc", line 144, in wrapper

        File "circuitscape\compute.pyc", line 27, in compute

        File "circuitscape\profiler.pyc", line 144, in wrapper

        File "circuitscape\compute.pyc", line 37, in compute_network

        File "circuitscape\profiler.pyc", line 212, in wrapper

        File "circuitscape\compute.pyc", line 124, in read_graph

      RuntimeError: Error processing graph/network file.  Please check file format

     

      

      

 

Calculating current flow centrality using Circuitscape (2nd try)...

     Calling Circuitscape:

 

Circuitscape failed.

      Traceback (most recent call last):

        File "csrun.py", line 13, in <module>

        File "circuitscape\profiler.pyc", line 144, in wrapper

        File "circuitscape\compute.pyc", line 27, in compute

        File "circuitscape\profiler.pyc", line 144, in wrapper

        File "circuitscape\compute.pyc", line 37, in compute_network

        File "circuitscape\profiler.pyc", line 212, in wrapper

        File "circuitscape\compute.pyc", line 124, in read_graph

      RuntimeError: Error processing graph/network file.  Please check file format

     

      

      

 

---------------------------------

ERROR: No Circuitscape output found.

It looks like Circuitscape failed.


---------------------------------

****Failed in step 7. Details follow.****

---------------------------------

Python error on **line 160** of s7_centrality.py in Linkage Mapper Version 2.0.0:

SystemExit: 1

Completed script CentralityMapper...

Failed to execute (CentralityMapper).

Failed at Mon Jun 29 17:03:53 2020 (Elapsed Time: 3.50 seconds)

 

Would very much appreciate if you could take a look into it,

Look forward to hear from you hopefully,

 

Thank you,

Best wishes,

<snip>

**Comment by dkav** [comment]
Without the input data it is not possible to identify the underlying problem.
