### ISSUE TITLE
Update a sentence in LinkageMapper.tbx help

### ISSUE THREAD

**Issue by johngallo** [linkagescape/linkage-mapper#143]
In the Linkage Priority tool the helm message for Lowest Allowable Maximum Climate Analog Ratio on the "Value Curve"  has a sentance that currently reads:  "If the LPMCAR value is 0 (the default), then this makes an extremely steep curve on the right side of the Value Curve."

This is not wrong.  But, it would be much better to instead read: "If the _Target Climate Analog Ratio_ is the default value of 1, and the _Relative Priority of Achieving the Targeted Ratio_ is the default value of 1, then this makes an extremely steep slope on the right side of the Value Curve. "

At least the change has been made in the white paper.

**Comment by dkav** [comment]
The change has been made to local tbx. Pending commit will close issue.
