### ISSUE TITLE
Climate Linkage Mapper is not working with ArcGIS 10.8.1

### ISSUE THREAD

**Issue by venkanna37** [linkagescape/linkage-mapper#151]
Climate Linkage Mapper is not working with the latest version of ArcGIS (v10.8.1). But, it is working fine with ArcGIS 10.7.1, 10.6.1, and ArcGIS Pro 2.81.

![Climate_Linkage_Mapper_Error](https://user-images.githubusercontent.com/29403196/131845077-db153224-de55-49ce-bcb9-991e9a2aef5d.png)
Screenshot from @johngallo 

PFA log file
[2021_08_03_1644_Climate Linkage Mapper(1).txt](https://github.com/linkagescape/linkage-mapper/files/7098961/2021_08_03_1644_Climate.Linkage.Mapper.1.txt)

**Comment by johngallo** [comment]
Thanks. Given the context, it is hopeful that this will be fixed when v10.8.2 comes out.

**Comment by venkanna37** [comment]
Some information regarding changes in the latest version of ArcGIS (v10.8) can find in the below link. They have modified the Costpath function in the new version by adding a new parameter to it. Even though that parameter is optional, costpath function is not working with the Climate Linkage Mapper inputs and this needs to fix.

Check Spatial Analyst toolbox section:
https://desktop.arcgis.com/en/arcmap/latest/get-started/introduction/whats-new-in-arcgis.htm

cc: @indranil-wii

**Comment by venkanna37** [comment]
Thank you so much @dkav, I spent a lot of time fixing this but I was not able to do it. I tested CLM and other tools on Arc 10.8.1 and Arc Pro 2.8.1 with this updated code,  all tools are working fine. So, I merged the code and closed the issue.

cc @johngallo

**Comment by johngallo** [comment]
Thanks Darren!
