### ISSUE TITLE
Quantifying the linkage priority values for Core Area Pairs based on their Climate Signature Values and Difference (Shortname = Climate Analog)

### ISSUE THREAD

**Issue by johngallo** [linkagescape/linkage-mapper#16]
A feature requested from the Mexico CONABIO team.  Here is my paraphrase, from the e-mail dialog below:  "The user can determine if they are mapping connectivity for the
near-term, and use your formula, or connectivity for the long term and
allowing for range shifts, and use the original formula."

here is "your forumla" fromthe below e-mail:

**> > We think the faster solution is to modify the line #534 in the
"lp_main.py" script:

diff_clim_env = abs(x_clim_env - y_clim_env)

         to
diff_clim_env = 1- abs(x_clim_env - y_clim_env)**

**Comment by johngallo** [comment]
Background and suggested code, in Bold.  read from the bottom up.  
On Fri, Jan 19, 2018 at 9:28 AM, Oscar Godinez Gomez <
ogodinez@conabio.gob.mx> wrote:

> Hi John,
> 1) Ok, I will hold off.
> 2) It sounds right. Respect to GitHub, I totally agree, please do it, It's
> a minimal change in the script but It can be useful. I have no problem with
> leaving the name, but I leave it to your consideration :)
>
> Thanks a lot!
>
> Oscar
>
>
>
> ----- Mensaje original -----
> De: "John Gallo" <john.gallo@consbio.org>
> Para: "Oscar Godinez Gomez" <ogodinez@conabio.gob.mx>
> Enviados: Miércoles, 17 de Enero 2018 19:23:55
> Asunto: Re: Climate linkage mapper and Linkage Priority mapper
>
> HI Oscar,
>
> Great to hear.
>
> 1) She might be doing the fix tomorrow, so you may want to hold off a bit
> before trying to do it manually.
> 2) I think your idea is a good one to put as a parameter for a future
> version.  The user can determine if they are mapping connectivity for the
> near-term, and use your formula, or connectivity for the long term and
> allowing for range shifts, and use the original formula.
>
> Does that sound right?  Can I copy a portion of this thread to a "feature
> request issue" in GitHub? Do you want me to remove your name or leave it
> in?
>
> Thanks,
>
> John
>
>
> On Wed, Jan 17, 2018 at 4:59 PM, Oscar Godinez Gomez <
> ogodinez@conabio.gob.mx> wrote:
>
> > Hi John,
> > Thanks! Happy new year!
> >
> > Perfect! It's a good new! And that's much better and faster than my
> > solution. I first run the climate linkage mapper tool and after I had to
> > copy some outputs (CWD, lcpLines_s3-s4, etc.), then I executed the
> "normal"
> > Linkage mapper tool and finally, I got the same corridors and I executed
> > the Linkage priority. A total chaos my solution jaja
> > It will help us a lot! First I will try to apply the solution manually
> > following Ana's comments.
> > New version! it will be great.
> >
> > Respect linkage priority, do you remember we talk about to give more
> > weight to corridors between cores that they don't have much difference in
> > the climate signature?
> >
**> > We think the faster solution is to modify the line #534 in the
> > "lp_main.py" script:
> >
> > diff_clim_env = abs(x_clim_env - y_clim_env)
> >
> >             to
> >
> >
> > diff_clim_env = 1- abs(x_clim_env - y_clim_env)**
> >
> >
> > Let me know what do you think.
> >
> > Thanks a lot.
> >
> > Cheers,
> > Oscar
> >
> >
> > ----- Mensaje original -----
> > De: "John Gallo" <john.gallo@consbio.org>
> > Para: "Oscar Godinez" <ogodinez@conabio.gob.mx>
> > Enviados: Martes, 16 de Enero 2018 17:18:36
> > Asunto: Climate linkage mapper and Linkage Priority mapper
> >
> > Hi Oscar,
> >
> > Happy New Year!
> >
> > Just wanted to let you know we are almost done fixing that issue you
> found
> > last year:  https://github.com/linkagescape/linkage-mapper/issues/4
> >
> > Further, if you wanted to do the workaround manually now, you could move
> > forward with it based on Annie's comments.  otherwise, a fixed version is
> > due out real soon1
> >
> > Cheers,
> >
> > John
> >

**Comment by johngallo** [comment]
- We will likely want to make a more exact equation than the one above that is trying to match the current* climate envelope of one core with the *future* climate envelope of the destination core.

- Add an option in the GUI to choose one, or the other, or neither.

- Add details in the user guide explaining the different types of connectivity (long term range shift in wide linkages, in which the species, often a plant, can live in the linkage), versus more narrow linkages used primarily for movement, so the climates of the cores need to be more similar.

**Comment by johngallo** [comment]
new paper on climate analogs: https://onlinelibrary.wiley.com/doi/pdf/10.1111/gcb.14373 and the .pdf is here:  http://www.cacpd.org.s3-website-us-west-2.amazonaws.com/Carrolletal2018/Carrolletal2018.pdf

**Comment by johngallo** [comment]
Potential parameter text:  "Which climate-wise feature do you want to address in this model run?"  Chouces would be:  1) Long term Range Shift (current algorithm) or 2) Climate Analog Approach or 3) None.

**Comment by johngallo** [comment]
Note the rename of this issue to make it more tight and more clear.  See also more specifications in this google doc, fleshing out he bullets of the June 22nd comment.

**Comment by dkav** [comment]
Completed with commit f81a4785ad8ab890cc61fb3f50cde15ce79ad0d7.
