### ISSUE TITLE
New Error message (first time using LinkageMapper 3.0.0

### ISSUE THREAD

**Issue by linhunt** [linkagescape/linkage-mapper#163]
Target core areas for core area #1 = [227 229 230 233 239 241 243 245 251]
Found an intermediate core in the least-cost path between cores 1 and 227.  The corridor will be removed.
---------------------------------
Geoprocessing error on **line 739** of lm_util.py in Linkage Mapper Version 3.0.0:
 
---------------------------------
ERROR 999999: Error executing function.
Failed to execute (RasterToPolyline).

---------------------------------

********************************************************
NOTE: ArcGIS errors are more likely when writing to remote drives or deep file structures. We recommend shallow project directories on local drives, like C:\puma. Errors may also result from conflicts with anti-virus software (known problems with AVG). We have also seen conflicts when writing to synchronized folders like DROPBOX.

Note also that Linkage Mapper tools often work best when run from ArcCatalog instead of ArcMap. 
 
---------------------------------
A record of run settings and messages can be found in your log directory:
C:\Users\lhunt\Desktop\Linkage_Mapper_2_0_0\run_history\log
---------------------------------
 
Completed script MapLinkages...
Failed to execute (MapLinkages).
Failed at Mon Jun 27 11:16:06 2022 (Elapsed Time: 8 minutes 12 seconds)

**Comment by johngallo** [comment]
please post questions and error log to the google group:
https://groups.google.com/u/3/g/linkage-mapper   Thank you!


John Gallo, Ph.D.
Senior Scientist
Conservation Biology Institute <https://consbio.org/people/staff/john-gallo>
136 SW Washington Avenue, Suite 202
Corvallis, OR 97333
Remote Office: Inglenook, CA
Phone: 707.962.9078
Twitter: @johnagallo <https://twitter.com/johnagallo>
Updates: Action Research Newsletter
<https://consbio.us9.list-manage.com/subscribe?u=3dea159e4cbe0a0ff3b43eadd&id=e3bd82fd81>

**Comment by johngallo** [comment]
Assuming that this was addressed in the google group or via email.
