### ISSUE TITLE
Failed to run using the linkage mapper version 2.0.0 in ArcGIS version 10.6

### ISSUE THREAD

**Issue by wxy23116** [linkagescape/linkage-mapper#174]
Hello，I used the linkage mapper version 2.0.0 in ArcGIS version 10.6 for build network and linkages analysis, and the result showed that it failed to run (there are no scripts related to this tool). What's going on here

**Comment by johngallo** [comment]
Please go to linkagemapper.org and get the latest version of the software.
IF that does not solve, use the community support forum also linked frm the
webpage.  Good luck!
