### ISSUE TITLE
linkage mapper

### ISSUE THREAD

**Issue by qidi9707** [linkagescape/linkage-mapper#175]
Python error on **line 111** of circuitscape_master.py in Linkage Mapper Version 2.0.0:
RuntimeError: Object: \u8bbf\u95ee\u73af\u5883 <extent> \u65f6\u51fa\u9519
Completed script PinchMapper...
执行(PinchMapper)失败。
失败 在 Fri Jan 26 11:07:08 2024 (经历的时间: 0.49 秒)

**Comment by johngallo** [comment]
Please use Linkage Mapper v 3.1.0 or the latest version available when this message is read.  You can get the latest version at linkagemapper.org

**Comment by qidi9707** [comment]
ok，谢谢
