### ISSUE TITLE
Update the Linkage Pathways Tool tool help

### ISSUE THREAD

**Issue by dkav** [linkagescape/linkage-mapper#28]
The Linkage Pathways tool needs to be reviewed and updated to match the latest developments.

**Comment by dkav** [comment]
Also, there are some visible formatting `<P>` tags in the help section of some of the _Additional Options_ parameters that need to fixed.

**Comment by johngallo** [comment]
from @rgreenefl : - The section title and text for sections 7 and 8 in the LP user guide appears incorrect.

**Comment by dkav** [comment]
@johngallo this is separate issue.

**Comment by johngallo** [comment]
@dkav OK, thanks for flagging my comment as for a seperate issue! I moved it to the beta testing issue and deleted it and your flagging comment.
