### ISSUE TITLE
Results from climate linkage mapper incompatible with LPM

### ISSUE THREAD

**Issue by aprisbrey** [linkagescape/linkage-mapper#4]
Issue - results from climate linkage mapper cannot be used with linkage priority mapper.

I used the demo datasets to try to reproduce the issue and encountered issues specific to the demo that should be fixed in addition to two issues with climate linkage mapper itself and then CLM in conjunction with LPM. I'll put the demo problems in another issue.

**CLM/LPM Issues**

**Issue 1**: Climate linkage mapper tuple error
CLM starts using cc_main.py and jumps over to lm_config.py:

https://github.com/linkagescape/linkage-mapper/blob/4ca80b44c2269fe3e691c0102f0da5e2099ca002/toolbox/scripts/lm_config.py#L238-L259

Lines 248-252 are trying to access arguments 19-22 when the user is using ArcGIS 10.x; however, the climate linkage mapper GUI does not have these variables as inputs, so there is nothing to feed in here, and the user gets a tuple index error:
![tuple_error](https://user-images.githubusercontent.com/33137709/34418518-c4b7e198-ebbb-11e7-9dda-c70b329b4edd.PNG)

I fixed this for test by changing the variables to the hardcoded values in lines 254-259. To avoid this issue the GUI should either be updated to accept these variables or they should be hardcoded like they are for earlier versions of ArcGIS.

**Issue 2**: Parameters error

My guess is that this is the main issue that is causing CLM and LPM to be incompatible.
![params_error_2](https://user-images.githubusercontent.com/33137709/34418609-2f1a9e68-ebbc-11e7-9ce1-ec9e42efb691.PNG)

https://github.com/linkagescape/linkage-mapper/blob/4ca80b44c2269fe3e691c0102f0da5e2099ca002/toolbox/scripts/lp_main.py#L143-L152

These lines (147 specifically) are searching the log file generated by linkage mapper for parameters that begin with a left bracket. When linkage mapper runs, it creates a list of the parameters in the log file and so they are enclosed in brackets. However, when climate linkage mapper generates its log file, it generates a tuple and therefore encloses the parameters with parentheses. 

Compare cc_main.py here (specifically 111-114 - setting lm_arg as a tuple)
https://github.com/linkagescape/linkage-mapper/blob/4ca80b44c2269fe3e691c0102f0da5e2099ca002/toolbox/scripts/cc_main.py#L109-L128

to lm_util.py here (specifically 1243 - writing parameters as a list):
https://github.com/linkagescape/linkage-mapper/blob/4ca80b44c2269fe3e691c0102f0da5e2099ca002/toolbox/scripts/lm_util.py#L1230-L1243

So cc_main.py should either be changed to generate a list of parameters in the log_file rather than a tuple, or lp_main.py should be changed to search for both. The former would maintain more consistency.

I changed the parentheses to brackets in the log file for climate LM just to keep testing, and after that I ran into no further issues running LPM with the outputs from climate LM. I also ran into no issues running pinchpoint mapper or barrier mapper with the climate LM outputs.

**Comment by rgreenefl** [comment]
Issue 1: My inclination is to hardcode default values for these as suggested by @aprisbrey when using CLM, as that would reflect the state of things when CLM was developed.

Issue 2: I concur with @aprisbrey assessment that the cc_main.py change to generate a list of parameters instead of a tuple would be more consistent. I'm not aware of other code-based uses of the log file that would be impacted, but perhaps @dkav could weigh in before Annie makes the change.

**Comment by dkav** [comment]
Brad added the log file code, so I cannot speak too directly. That said, the suggested solution seems reasonable to me.

**Comment by johngallo** [comment]
OK, great write up Annie, thanks for taking a look Randal and Darren! I am on vacation now but don't want to slow momentum. I'll defer to you all on this one. Annie please let us know if there's anything else you have questions about before you take a stab at this. Unless I am misunderstanding, in which case give me a call.

**Comment by aprisbrey** [comment]
I've fixed the errors for now - I changed cc_main.py to reflect the parameter instead of tuple change, and I added a config_cc function in lm_config.py to hardcode those last four variables. I would have preferred to do a logic within the config_lm function to check whether it was running climate or normal linkage mapper and chosen to hardcode or pull arguments respectively, but I had a hard time figuring out how to do that. For now I've just committed that change to lm_config.py but haven't pushed it yet; I pushed the first change to cc_main.py.

**Comment by johngallo** [comment]
Annie, Great! If I understand correctly, you've made a change to lm_config.py on your local machine that is not pretty but would get the job done.  Is that correct? and you've made a change to cc_main.py that is pushed, so is now part of the code, so if I download the code from the v2.0.0dev fork I'd see it implemented? If this is all the case, it seems to me that you can go ahead and push the lm_config.py change so we can begin testing, and if someone wants to do a more elegant solution, they can do it later. @rgreenefl @dkav  @nikmolnar please correct me if I am wrong in my assumptions that (this will work ok, even if you want to do something more elegant later.)  @aprisbrey if you do not hear any "nays" within 24 hrs, or hear all "ayes" please move forward with that option.  Thanks!

**Comment by dkav** [comment]
@aprisbrey neither of your changes appear to have been pushed. 

Looking at the code some more, I think the easiest option to deal with the missing parameters is to just append the argument line in cc_main.py. https://github.com/linkagescape/linkage-mapper/blob/d85c41b3f67631f84ede7120f58059e3efb78604/toolbox/scripts/cc_main.py#L111-L114 CLM was not developed for ArcGIS version 9 and so hardcoding in this location is appropriate.

**Comment by aprisbrey** [comment]
@dkav I am wondering if with your suggested fix it will still run into the issue when it hits here in lm_config.py:
https://github.com/linkagescape/linkage-mapper/blob/d85c41b3f67631f84ede7120f58059e3efb78604/toolbox/scripts/lm_config.py#L248-L259

**Comment by dkav** [comment]
@aprisbrey it shouldn’t run into an issue as it will have the correct number of parameters. For example:

lm_arg = [_SCRIPT_NAME, cc_env.proj_dir, cc_env.prj_core_fc, 
           cc_env.core_fld, cc_env.prj_resist_rast, "false", "false", "#", 
           "#", "true", "false", cc_env.prune_network, cc_env.max_nn, 
           cc_env.nn_unit, cc_env.keep_constelations, "true", "#", "#", “#”, “#”, “true”, “200000”,  “#”]

(The non-variable parameters should probably be converted to constants and be defined in the config file. Particularly the CWD threshold.)

**Comment by aprisbrey** [comment]
@dkav Gotcha, thanks - what is the benefit to defining those in the config file in addition to appending the argument line in the main file? I had originally just hardcoded them in the config under a new section for config_cc that was a whole copy of config_lm without the option of passing variables for the last 4 arguments, just hardcoded.

**Comment by aprisbrey** [comment]
For now I made the changes to the arguments in cc_main and pushed those through to v2.0.0dev.

**Comment by dkav** [comment]
@aprisbrey I am not exactly clear on your change. That said, the main benefit in my mind is clarity. Code could look the following:

In cc_main.py -
```
lm_arg = [_SCRIPT_NAME, cc_env.proj_dir, cc_env.prj_core_fc, 
           cc_env.core_fld, cc_env.prj_resist_rast, "false", "false", "#", 
           "#", "true", "false", cc_env.prune_network, cc_env.max_nn, 
           cc_env.nn_unit, cc_env.keep_constelations, "true", "#", "#", “#”, “#”, 
	   cc_env.OUTPUTFORMODELBUILDER , cc_env.WRITETRUNCRASTER, 
           cc_env.CWDTHRESH, cc_env.LMCUSTSETTINGS]
```
In cc_config.py -
```
self.OUTPUTFORMODELBUILDER = "#"
self.WRITETRUNCRASTER = "true"
self.CWDTHRESH = "200000"
self.LMCUSTSETTINGS = "#"
```

N.B. For convenience I didn’t include constants for the other inputs.

(It appears that lm_config is using uppercase for configuration variables and cc_config is using lowercase. I will added this as a [minor issue](https://github.com/linkagescape/linkage-mapper/issues/8).)

**Comment by aprisbrey** [comment]
@dkav I had changed the parameters per your message from an hour ago. I just updated it now to reflect your most recent message.
