### ISSUE TITLE
Make directory structure of repository match that of the build

### ISSUE THREAD

**Issue by johngallo** [linkagescape/linkage-mapper#55]
Or vice versa.  As is, it is annoying to make any new release (wasting time).  It also leads to errors in beta testing, like relative path to files in the demo folder in the repository, which gets renamed as LP_Demo folder in the build, or something like that.

**Comment by johngallo** [comment]
probably best to keep the builds repository structure the same, so the users do not notice a difference.  Unless there is a big reason to do otherwise.

**Comment by johngallo** [comment]
darren advocates for the script.  Also, maybe modify the task to first look at the build script and what it would take to get it up to date and report out?.  Also, how hard is it to implement?  I often find myself at conferences/multi-day workshops where i need to push out a hotfix and new build for the participants, so I would need to be able to run the script too.  I used to do python, but it has been a while...

**Comment by dkav** [comment]
The repo structure is setup for software development not distribution. We can update the build script to make it easier to produce builds. Issues #133 can be used to track this update. Modifying the structure to replicate the build will also be compatible with #132.
