### ISSUE TITLE
Move Truncate Options into Step 5 

### ISSUE THREAD

**Issue by dkav** [linkagescape/linkage-mapper#6]
I think the now visible truncate options should be moved up into Step 5 within the toolbox. The Additional Option section is to my mind only for optional options. CLM (and other files) would have to be amended to reflect the change in parameter order if the update was made.

https://github.com/linkagescape/linkage-mapper/blob/d85c41b3f67631f84ede7120f58059e3efb78604/toolbox/scripts/lm_config.py#L248-L259

**Comment by rgreenefl** [comment]
Good point @dkav, the final three parameters are actually used in step 5. Our logic was to move newly-daylighted parameters, to hopefully maintain compatibility with old runs in users' run history. If the proposed change is undertaken, the parameter order/indexes would be different between 9.3 and 10.x and that would be need to be accounted for (or 9.3 support dropped altogether).

**Comment by johngallo** [comment]
@rgreenefl and/or @dcav or anyone else:  Given that most people are on 10.x, how would you recommend we account for this?  Could it be done easily by a hotlink in the user guide(s) to a dynamic web page that is titled something like "Trying to run Linkage Mapper V 2.x (2018+) in Arc GIS 9.3 (200X)?  Here is what you can still do out "of the box" and some "workarounds" to do more."  (X= Anyone know what year 9.3 came out?)  Also, what are some of the other the dependencies to implementing the above before public release?  New screengrabs in the user guide for one. Others?

**Comment by rgreenefl** [comment]
The history of ArcGIS release dates is at [https://en.wikipedia.org/wiki/ArcGIS](url).

If I were going to put any effort into supporting anything other 10.x 32-bit, it would be for 64-bit and ArcGIS Pro.

**Comment by dkav** [comment]
I would advocate removing support for 9.x in LM 2.x. If this path is chosen, I think code written to accommodate 9.x should be removed from the code base as well. For example, the continued use of arcgisscripting and the use of gp over arcpy. Other than those previously mentioned, the only other dependencies that I can think of are script files that run the tools outside of ArcMap.

You could continued to support 9.x without 2.x's new features. This would require creating a separate but maintained branch from the existing master branch, while also providing a build from this branch. Obviously, a 9.x installation for testing would be required too.

**Comment by johngallo** [comment]
@rgreenefl  we've decided this is a medium priority, greatly improving the release and little work.  @dkav can do it if you do not have time, unless you want to tackle it.  Can you let us know?

**Comment by rgreenefl** [comment]
Sorry, I can't commit to taking this on, because I'm not confident how long it will take given testing, impacts on CLM, 9.3 compatiblity, etc.

**Comment by johngallo** [comment]
That is OK, thanks for letting us know.  @dcav will leave it to you to prioritize this compared to the other issues.

**Comment by johngallo** [comment]
@dcav  after you code this, one of us will need to update the screengrabs in the user guide (user guides?) with the new view.  Please do this or assign it to me before we close this issue.  Or ye we should be granular and close this issue after the coding, and open another one to update the user guide(s).

**Comment by dkav** [comment]
Testing right now. I have updated the text and side graphics in the guide but my screen is not large enough (without scaling) to grab a full length toolbox. So you will need to make that update for me. You can just add an extra commit to the branch that I will push.

P.S. It's @dkav. You are linking to someone else on GitHub with 'dcav'.

**Comment by johngallo** [comment]
sorry bout that.  just added it to the issues.
