### ISSUE TITLE
move repository to a location without a dash to facilitate dev

### ISSUE THREAD

**Issue by johngallo** [linkagescape/linkage-mapper#64]
The multi-tool combinations are best built and tested in the repository.  I made a demoOutputs folder in the repository to do this, and also added a line to .gitignore to ignore that repository.  But that cannot happen as the repository is currently names:

"Setting data frame spatial reference to that of core area feature class.
ERROR: Project directory cannot contain spaces, dashes, or special characters.
---------------------------------
A record of run settings and messages can be found in your log directory:
D:\GIS\Repositories\linkage-mapper\demo\demoOutputs\v4ClimateFocus\run_history\log
"
so, how about if we make a new repository named linkagemapper instead of linkage-mapper
@dkav do you think this will be OK?

**Comment by dkav** [comment]
If I understand correctly, I don't see why you cannot use a project folder outside of the repository. This is what I do. Moreover, the root folder (linkage-mapper) of your repository can have any name you like (e.g. clone https://github.com/linkagescape/linkage-mapper.git test) and can be renamed after cloning.

**Comment by dkav** [comment]
If you want to ignore files locally (and not change the project ignore) edit [.git/info/exclude](https://stackoverflow.com/questions/1753070/how-do-i-configure-git-to-ignore-some-files-locally).

**Comment by johngallo** [comment]
Thanks!  At issue is the way the Multi-Tool Combination tools are built with nested tools that rely on relative paths to both the input data and the outputs.  This idea allows for faster creation of the builds (less steps to remember).  I'll try renaming the linkage-mapper folder of my repository after I push through the latest round of fixes.

**Comment by dkav** [comment]
I don't think the tools should hard-code project folder parameters (or any input parameter for that matter). Also, I would separate out internal testing requirements from build requirements.

**Comment by dkav** [comment]
Issue being closed for the same reasons stated in https://github.com/linkagescape/linkage-mapper/issues/55#issuecomment-808840956.
