### ISSUE TITLE
On new feature, Core_start and Core_end not calculating properly

### ISSUE THREAD

**Issue by johngallo** [linkagescape/linkage-mapper#65]
Hello Darren,

I think I found a bug/error in the new code implementation.  

Climate Analog Ratio is not calculating correctly for the linkages in which the hotter/drier core aree is the higher core_id compared to the other core area.  I think that is the issue.  I suspect that the code for determining Core_Start and Core_End needs to be revised.

Here is what I see, using the modoc demo data:

The _LCPs output file:
![image](https://user-images.githubusercontent.com/16655595/46703902-943c7080-cbdd-11e8-8824-0e2a19e8386c.png)

and the output values in the cores file:

![image](https://user-images.githubusercontent.com/16655595/46703858-635c3b80-cbdd-11e8-9a72-90a4c4e9f831.png)

By my calculations, core 2 is hotter/drier than core 1 at the current time, so core 1 should be the Destination Core (Core_End).  Therefore the C Analog ratio is the climate of core 1 in the future, divided by the climate of core 2 in the present = 608/660 = .9212 not 1.25  .  I think that 1.25 occurs because core 1 is marked as the start core.

I checked the linkage of cores 1 and 4, and in this case 1 is hotter, so core start and core end are correct, and the CAnalog ratio is 445/5553 = .804 which is what we get.

I note that Core_Start and Core_end exactly replicate From_Core and To_Core so that might be a hint in the troubleshooting.  Please let me know if I should clarify more or anything.  Thanks!

**Comment by dkav** [comment]
Fixed in 8cf45325d1bc1e75a65ea25cdf8353c0f3570a1c.

(I am not sure I would assign issues for features still in active development.)
