### ISSUE TITLE
Extraneous Comment Section?

### ISSUE THREAD

**Issue by dkav** [linkagescape/linkage-mapper#7]
@rgreenefl is this commented section still required?

https://github.com/linkagescape/linkage-mapper/blob/d85c41b3f67631f84ede7120f58059e3efb78604/toolbox/scripts/lm_config.py#L261-L278

**Comment by rgreenefl** [comment]
@dkav, these changes predate CBI's involvement in the project. I think they can go...

**Comment by dkav** [comment]
@rgreenefl I will make the change. Thanks!

**Comment by johngallo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [APPROVE dARREN'S PULL REQUESTS](https://trello.com/c/ckZR8S6m/110-approve-darrens-pull-requests)

**Comment by aprisbrey** [comment]
Darren's pull requests approved and merged. Associated branch deleted.
