### ISSUE TITLE
Pinchpoint Mapper Failing

### ISSUE THREAD

**Issue by ochotona** [linkagescape/linkage-mapper#75]
I am doing the LM_Lab and each time I try to run the Pinchpoint Mapper in Step 3, it fails. I have restarted ArcMap numerous times and made sure that I am following the tutorial exactly, but it doesn't resolve this issue.

I'm using Windows 10.0 64 bit, ArcMap 10.6, and Linkage Mapper 2.0.0.

I've included an image of the failed message below:

![pinchpoint_error2](https://user-images.githubusercontent.com/15622956/53620899-7a5df300-3ba9-11e9-8c83-2de38f2a5794.png)

**Comment by johngallo** [comment]
Hello Ochotona,  

Please send the full log file and or select all text in the above dialog, copy, paste into a text file, and send that.

You might also want to search the communtiy forum for similar issues and resolutions: https://groups.google.com/forum/#!forum/linkage-mapper 

Thanks,

John

**Comment by ochotona** [comment]
Hi John,

Thank you for your response, and for sending me the link to the Google Group community.

I reinstalled everything, and it all seems to be working now.
