### ISSUE TITLE
Blended priority only in new beta releases

### ISSUE THREAD

**Issue by meganjennings** [linkagescape/linkage-mapper#79]
I've just tried the LP tool in several of the beta releases, and when the run is complete, the only output added to the corridor geodatabase in my project folder is the blended priority. None of the other outputs are being written to that gdb. 

I started with beta release 5, and then also tried 2 and 4, and no luck.
I verified in lp_settings.py that the I had the following:
`CALCCSPBP = 2  # No_Calc=0, CSP=1, CSP_BP=2`

It looks as though selecting option 2 should trigger production of the blended priority as well as the other outputs to the corridor.gdb, but I can't seem to get those outputs. 

Ideas? Please let me know if you'd like me to send a log file or other output. 
Thanks!

**Comment by johngallo** [comment]
Hello Megan,

We made an change to the algorithm at 2.1.0beta-2 that improves the way that linkage priority is integrated into the process.  (See the google doc linked from the issues linked from the beta3 release) https://github.com/linkagescape/linkage-mapper/releases/tag/v2.1.0-beta.3 

If you would like an output which is the corridors mapped (i.e. braided and with varying widths) and symbolized by their linkage priority value, then you have two options. 

You can run the linkage priority tool in beta2 through beta5 (beta5 is most stable) with a weight of 1 for the linkage priority factor, and a weight of 0 for the least cost corridors.  You can then manually combine that output with the regular corridors_truncated at X output the way we did in the past.

Alternatively (not recommended) you can run it on beta-1 the old fashioned way, which should give the same set of outputs as v 2.0.0.  If you want me to elaborate on why this option is not recommended please let me know.

Thanks,

John

**Comment by johngallo** [comment]
Also, if that did not answer the issue sufficiently please re-open the issue. I'm closing it for now to keep open issues tidy. Thanks Megan.
