### ISSUE TITLE
Cannot find an installation of Circuitscape in your Program Files directory.

### ISSUE THREAD

**Issue by z292389919** [linkagescape/linkage-mapper#80]
Hello, experts,when I run pinchpoint mapper,displayed an error: Cannot find an installation of Circuitscapein your Program Files directory.Before that, I could run Build Network and Map Linkages successfully.  I would appreciate it if you could answer my question.

**Comment by johngallo** [comment]
Hello Z,

I believe it mentions in the pinchpoint mapper user guide that circuitscape will need to be installed separately, from another location.  Currently, that location is : https://circuitscape.org/downloads/ and be sure to use version 4 (i.e. 4.0.5) if you want the version that is known to be compatible with Linkage Mapper.  V5 is written in Juluia and needs to be testd and integrated with Linkage Mapper still.  

OR, if you would like the most current version with a bit more error message detail, you can use v4.0.6 which is not formally published yet, but is [here](https://drive.google.com/file/d/1eDCRWjhZRtUU0hPuccCU_uVvSProMSHM/view), and is based on this [issue](https://github.com/Circuitscape/Circuitscape/pull/93).

Thanks,

John

P.S. Am closing the issue. If you would like like to discuss it further, please re-open the issue. Thanks.
