### ISSUE TITLE
"Do you want to continue running scripts on this page?" (in LM GUI) Replicate, Diagnose (and fix?) Error: 

### ISSUE THREAD

**Issue by johngallo** [linkagescape/linkage-mapper#82]
Error report: see https://groups.google.com/d/msg/linkage-mapper/bCdOW8V5mxQ/XhEGSurjAQAJ

I remember that from many years ago.  Perhaps it is with particular Active X settings. Or a particular version of Windows set up.

**Comment by dkav** [comment]
This is an ESRI/Microsoft issue and it would appeared to resolved in recent versions of ArcGIS Desktop. See [Bug: Internet Explorer script errors are generated when running any geoprocessing tool from ArcToolbox on some systems that implement folder redirection](https://support.esri.com/en/technical-article/000011008). See also [this Stack Exchange answer]( https://gis.stackexchange.com/a/122954).
