### ISSUE TITLE
Fix the Multi-tool Combination 

### ISSUE THREAD

**Issue by johngallo** [linkagescape/linkage-mapper#84]
It may be best to move the multi-tool combination into a new toolbox called LM Utilities Beta, or something like that. You can add the other combo tools that are under development.

In the meantime, remove red X's in Multi-tool combination by opening and closing in arc map, at the least, 
also fix a weight which was 0.02 but should have been 0.33 to be equal as the others.

**Comment by johngallo** [comment]
The one that was fixed, but could not be cherrypicked is here on Gallo's machine E:\GIS\Repositories\NotSynchedWithGIT

**Comment by johngallo** [comment]
meanwhile, I just realized that it looks like this commit was actually included, and rebased, and that is why it is a dangling head in Git Kraken: 
![image](https://user-images.githubusercontent.com/16655595/59069351-aef9de80-886b-11e9-8b8b-2319331dd77e.png)

**Comment by dkav** [comment]
Converting the toolbox from binary to Python (see issue #46) will allow much more flexibility with multi tools. Closing on this basis and because part of the documented issue was fixed.
