### ISSUE TITLE
LP Zonal Statistics Error - Invalid output extent

### ISSUE THREAD

**Issue by dkav** [linkagescape/linkage-mapper#9]
LP doesn't check if the outputs from Linkage Mapper share the same extent of the selected inputs. See attached log -

[lp_run_log_27012018.txt](https://github.com/linkagescape/linkage-mapper/files/1670791/lp_run_log_27012018.txt)

**Comment by johngallo** [comment]
we talked about this on our call:  John thinks the error message is probably OK for now.
