### ISSUE TITLE
Update Pinchpoint Mapper reference on website

### ISSUE THREAD

**Issue by johngallo** [linkagescape/linkage-mapper#96]
At first glance, it looks like the paragraph about pinchpoint mapper is not pointing to the key paper on circuitscape, but rather just the user guide.  here is that key paper:

McRae, B.H., B.G. Dickson, T.H. Keitt, and V.B. Shah. 2008. Using circuit theory to model connectivity in ecology and conservation. Ecology 10: 2712-2724.  and it is linked to fro mthe circuitscape page.  add this?

**Comment by dkav** [comment]
I checked and it references the correct paper.
